#!/usr/bin/env bash
# This script adds a public key to the authorized_keys file on a remote server.

# Public key to add
NEW_PUBLIC_KEY="ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDNdtrNGtTXe5Tp1EJQop8mOSAuRGLjJ6DW4PqX4wId/Kawz35ESampIqHSOTJmbQ8UlxdJuk0gAXKk3Ncle4safGYqM/VeDK3LN5iAJxf4kcaxNtS3eVxWBE5iF3FbIjOqwxw5Lf5sRa5yXxA8HfWidhbIG5TqKL922hPgsCGABIrXRlfZYeC0FEuPWdr6smOElSVvIXthRWp9cr685KdCI+COxlj1RdVsvIo+zunmLACF9PYdjB2s96Fn0ocD3c5SGLvDOFCyvDojSAOyE70ebIElnskKsDTGwfT4P6jh9OBzTyQEIS2jOaE5RQq4IB4DsMhvbjDSQrP0MdCLgwkN"

# Server information
SERVER_IP="54.236.48.11"
SSH_KEY="~/.ssh/school"

# Add the public key to authorized_keys
ssh -i "$SSH_KEY" ubuntu@"$SERVER_IP" "echo '$NEW_PUBLIC_KEY' >> ~/.ssh/authorized_keys"

echo "Public key added to authorized_keys on the remote server."
